(function () {
 'use strict';
 function init() {
  var old = document.getElementById('shop-journey'); if (!old) return;
  var source = window.allProducts || {}, basket = [], category = 'coques', query = '', limit = 8;
  var wa = text => 'https://wa.me/33783921884?text=' + encodeURIComponent('Bonjour Solution Phone, ' + text);
  var photo = (pattern, list) => ((list || source.coques || []).find(p => pattern.test(p.name)) || {}).img;
  var products = {
   coques: [
    {name:'Coque MagSafe', price:10, img:photo(/POLARIS.*MagSafe/), note:'L’anneau magnétique, le style en plus.'},
    {name:'Coque transparente classique', price:5, img:photo(/POLARIS 2M$/), note:'Votre téléphone, tout simplement.'},
    {name:'Coque couleur', price:10, img:photo(/PAVONE Rose Pastel/), note:'Une touche de couleur au quotidien.'},
    {name:'Coque à rabat', price:15, img:photo(/GAMMA/), note:'Le format portefeuille.'}
   ],
   verres:[{name:'Verre trempé classique',price:5},{name:'Verre trempé premium',price:10}],
   hydrogel:[{name:'Saphir',price:10,note:'Finition transparente'}, {name:'Privacy Onyx',price:10,note:'Finition confidentialité'}, {name:'Crystal',price:20,note:'Transparent haut de gamme'}, {name:'Obsidian Privacy',price:20,note:'Confidentialité haut de gamme'}, {name:'ECOSHIELD 7H',price:30,note:'Notre gamme premium 7H'}]
  };
  if(window.utopyaCases && window.utopyaCases.length) products.coques=window.utopyaCases;
  ['chargeurs','cables','audio','batteries','supports','accessoires'].forEach(k => products[k] = (source[k] || []).concat((window.utopyaAccessories||{})[k]||[]));
  var protectionImageBase='https://www.utopya.fr/media/catalog/product/cache/361213619c8483dcf525ed41a38dd6e5/';
  products.verres[0].img=protectionImageBase+'9/9/999--antichoc-v2_1_5.jpg';
  products.verres[1].img=protectionImageBase+'f/u/full3d.jpg';
  products.verres.forEach(p=>{p.note='Visuel illustratif · protection vendue à l’unité'});
  var filmPhotos={'Saphir':'8/1/811--774871_1.jpg','Privacy Onyx':'8/1/810--779811.jpg','Crystal':'8/1/811--774871_2_1.jpg','Obsidian Privacy':'8/1/810--779811_1_1.jpg','ECOSHIELD 7H':'1/-/1-ecoshield_1.jpg'};
  products.hydrogel.forEach(p=>{p.img=protectionImageBase+filmPhotos[p.name];p.note+=' · 1 protection posée';p.packshot=true});
  var root = document.createElement('main'); root.className = 'sf'; root.id = 'boutique';
  root.innerHTML = `<div class="sf-brandline"><b>Solution<span> Accessoires</span></b><span>Une boutique Solution Phone · Mâcon</span><a href="#sf-selection" class="sf-bag">Ma sélection <b id="sf-bag-count">0</b></a></div>
   <nav class="sf-nav" aria-label="Rayons de la boutique"><a href="#sf-products">Accessoires</a><a href="#sf-hydrogel">Protection hydrogel</a><a href="#sf-phones">Smartphones reconditionnés</a><a href="#sf-services">Services</a><a href="./#devis">Réparation urgente ↗</a></nav>
   <section class="sf-banners" aria-label="À découvrir en boutique" aria-roledescription="carrousel"><div class="sf-slides">
    <article class="sf-slide sf-peach"><div><span>LE BON ACCESSOIRE. LE BON TÉLÉPHONE.</span><h1>Votre téléphone.<br>Tout ce qui va avec.</h1><p>Coques dès 5 €, protections et smartphones reconditionnés. À choisir ici, à retrouver à Mâcon.</p><a href="#sf-products">Équiper mon téléphone →</a></div><div class="sf-collage" id="sf-collage"></div></article>
    <article class="sf-slide sf-blue"><div><span>UNE SECONDE VIE. VOTRE PROCHAIN CHOIX.</span><h2>Changez de téléphone.<br>Gardez vos habitudes.</h2><p>Reconditionnés garantis 12 mois. Notre équipe vous accompagne en boutique.</p><a href="#sf-phones">Voir les smartphones →</a></div><img src="img/iphone-models/2021-iphone12-colors.png" alt="Illustration de la gamme iPhone, sans indication de stock" width="450" height="330"></article>
    <article class="sf-slide sf-ink"><div><span>PROTECTION SUR MESURE</span><h2>Un bel écran.<br>Ça se protège.</h2><p>Hydrogel dès 10 € avec pose. Découvrez votre finition, jusqu’à ECOSHIELD 7H.</p><a href="#sf-hydrogel">Choisir ma protection →</a></div><div class="sf-screen-art" aria-hidden="true"><i></i><b>7H</b><span>ECOSHIELD</span></div></article>
   </div><div class="sf-controls"><button type="button" id="sf-prev" aria-label="Bannière précédente">←</button><span id="sf-slide-status" aria-live="polite">1 / 3</span><button type="button" id="sf-next" aria-label="Bannière suivante">→</button><small>La boutique de votre téléphone, depuis 2014 à Mâcon</small></div></section>
   <div class="sf-device"><div><b>On commence par votre téléphone ?</b><span>Votre modèle accompagne toute votre sélection.</span></div><label for="sf-device">Modèle de téléphone<input id="sf-device" list="sf-models" placeholder="Ex. iPhone 15, Galaxy S24…"><datalist id="sf-models"><option value="iPhone 15"><option value="iPhone 14"><option value="iPhone 13"><option value="iPhone 16"><option value="Samsung Galaxy S24"><option value="Samsung Galaxy S23"></datalist></label></div>
   <section id="sf-products" class="sf-section"><div class="sf-heading"><div><span>LES ESSENTIELS</span><h2>À chacun son style.</h2></div><form class="sf-search" role="search"><label for="sf-search">Rechercher un accessoire</label><div><input id="sf-search" type="search" placeholder="Chargeur, câble…"><button>Rechercher</button></div></form></div><nav id="sf-categories" class="sf-tabs" aria-label="Catégories d’accessoires"></nav><p class="sf-disclaimer">Choisissez votre gamme. Visuels illustratifs : les découpes varient selon le modèle. Compatibilité, coloris et disponibilité confirmés par l’équipe.</p><p id="sf-count" role="status"></p><div id="sf-grid" class="sf-grid"></div><button id="sf-more" class="sf-more">Voir plus de produits</button></section>
   <section id="sf-hydrogel" class="sf-section sf-protect"><div class="sf-heading"><div><span>DÉCOUPÉ POUR VOTRE ÉCRAN · POSÉ EN BOUTIQUE</span><h2>La protection qui vous ressemble.</h2><p>Transparent ou confidentialité. De 10 à 30 €, pose incluse.</p></div><a href="#sf-products" id="sf-show-glass">Plutôt verre trempé ? Dès 5 € →</a></div><div class="sf-film-grid" id="sf-films"></div></section>
   <section id="sf-phones" class="sf-section sf-stock-board"><div class="sf-board-heading"><span>LE TABLEAU DE LA BOUTIQUE · MÂCON</span><h2>Repérez votre prochain téléphone.</h2><p>Le stock disponible dans notre catalogue, sans détour. Garantie commerciale 12 mois, sans préjudice des garanties légales.</p></div><div class="sf-board-tools"><label>Rechercher dans le stock<input id="sf-stock-search" type="search" placeholder="iPhone 13, Samsung, 256…"></label><button id="sf-stock-refresh" type="button">Actualiser ↻</button></div><p id="sf-stock-status" role="status">Chargement du stock…</p><div id="sf-stock" class="sf-board-scroll" tabindex="0" role="region" aria-label="Tableau du stock disponible"><table class="sf-stock-table"><caption>Appareils reconditionnés disponibles · une ligne par appareil</caption><thead><tr><th scope="col">Modèle / capacité</th><th scope="col">État / batterie</th><th scope="col">Stock</th><th scope="col">Prix</th></tr></thead><tbody id="sf-stock-rows"></tbody></table></div><p class="sf-board-note">Lecture du catalogue toutes les minutes lorsque cette page est visible. Un délai de synchronisation est possible. La demande WhatsApp ne réserve pas l’appareil.</p><a class="sf-stock-help" target="_blank" rel="noopener">Besoin d’un conseil ? Parlons de votre prochain téléphone →</a></section>
   <section id="sf-selection" class="sf-section sf-selection"><div><span>VOTRE SÉLECTION, PAS UN PANIER À PAYER</span><h2>On vous prépare ça ?</h2><p>Ajoutez ce qui vous plaît. Envoyez une seule demande à l’équipe pour confirmer les produits avant votre passage.</p></div><div><ul id="sf-basket"></ul><p id="sf-total" role="status"></p><div class="sf-selection-actions"><a id="sf-send" class="sf-primary" target="_blank" rel="noopener">Envoyer ma sélection sur WhatsApp</a><a id="sf-mail">Envoyer par e-mail</a></div><small>Aucun paiement en ligne, aucune réservation automatique.</small></div></section>
   <section id="sf-services" class="sf-section"><div class="sf-heading"><div><span>UNE VRAIE ÉQUIPE, JUSTE À CÔTÉ</span><h2>Pas seulement un téléphone dans une boîte.</h2></div></div><div class="sf-services"><article><span>01 / TRANSFÉRER</span><h3>Gardez vos souvenirs.</h3><p>Photos, contacts, nouveau smartphone : nous étudions le transfert avec vous. Tarif confirmé avant intervention.</p><a data-service="je souhaite un transfert de données. Mes deux téléphones : ">Parler de mon transfert →</a></article><article><span>02 / REVENDRE</span><h3>Et votre ancien téléphone ?</h3><p>Demandez une estimation de reprise selon son modèle et son état.</p><a data-service="je souhaite une estimation de reprise. Mon téléphone : ">Faire estimer mon téléphone →</a></article><article><span>03 / NOUS RENCONTRER</span><h3>Rendez-vous à Mâcon.</h3><p>21 Rue Gambetta. Découvrez les produits avec l’équipe Solution Phone.</p><a href="#contact">Horaires, contact et itinéraire →</a></article></div></section>
   <aside class="sf-repair"><div><b>Votre smartphone est cassé ?</b><p>Solution Accessoires appartient à Solution Phone. Retrouvez aussi notre atelier de réparation.</p></div><a href="./#devis">Devis réparation urgente →</a></aside><p id="sf-announcement" class="sf-live" role="status" aria-live="polite"></p>`;
  old.before(root); old.hidden = true;
  for(var node = old.nextElementSibling; node && node.id !== 'contact'; node = node.nextElementSibling) if(/^(SECTION|ASIDE)$/.test(node.tagName)) node.hidden = true;
  var $ = s => root.querySelector(s);
  var filters=document.createElement('div');filters.className='sf-case-filters';filters.innerHTML='<label>Style<select id="sf-case-style"><option value="">Toutes les coques</option value="magsafe">MagSafe</option><option value="wallet">À rabat / portefeuille</option><option value="clear">Transparentes</option><option value="color">Couleurs & motifs</option></select></label><label>Marque<select id="sf-case-brand"><option value="">Toutes les marques</option><option>COVERME</option><option>FAIRPLAY</option><option>RHINOSHIELD</option></select></label><label>Trier<select id="sf-case-sort"><option value="">Notre sélection</option><option value="asc">Prix croissant</option><option value="desc">Prix décroissant</option></select></label>';
  $('#sf-grid').before(filters);filters.addEventListener('change',()=>{limit=12;render()});
  document.querySelectorAll('header a, footer a').forEach(a=>{var href=a.getAttribute('href');if(href==='reconditionnes.html')a.href='#sf-phones';if(href==='hydrogel.html')a.href='#sf-hydrogel';});
  function img(p) { var el=document.createElement('img');el.src=p.img;el.alt=p.name;el.loading='lazy';el.width=240;el.height=240;el.onerror=function(){this.hidden=true};return el; }
  function visual(p) { if(p.img)return img(p);var v=document.createElement('div');v.className='sf-product-art';v.setAttribute('aria-hidden','true');v.textContent=/Privacy|Onyx/.test(p.name)?'PRIVACY':/7H/.test(p.name)?'7H':'CLEAR';return v; }
  [products.coques[2], products.coques[0], products.coques[3]].forEach(p=>$('#sf-collage').append(img(p)));
  var cats=[['coques','Coques'],['verres','Verres trempés'],['hydrogel','Hydrogel'],['chargeurs','Chargeurs'],['cables','Câbles'],['audio','Audio'],['batteries','Batteries externes'],['supports','Supports'],['accessoires','Cordons & accessoires']];
  cats.forEach(([key,label])=>{var b=document.createElement('button');b.type='button';var p=products[key][0];if(p)b.append(visual(p));var caption=document.createElement('span');caption.textContent=label;b.append(caption);b.dataset.category=key;b.onclick=()=>{category=key;query='';$('#sf-search').value='';limit=12;$('#sf-case-brand').value='';$('#sf-case-style').value='';render()};$('#sf-categories').append(b)});
  var announcementTimer;
  function add(p,detail){var item=Object.assign({},p,{detail:detail||'',model:$('#sf-device').value.trim()});if(!basket.some(i=>i.name===item.name&&i.detail===item.detail&&i.model===item.model))basket.push(item);updateBasket();$('#sf-announcement').textContent=p.name+' ajouté à votre sélection.';clearTimeout(announcementTimer);announcementTimer=setTimeout(()=>{$('#sf-announcement').textContent=''},3500);}
  var dialog=document.createElement('dialog');dialog.className='sf-dialog';dialog.setAttribute('aria-labelledby','sf-detail-title');dialog.innerHTML='<button class="sf-close" aria-label="Fermer la fiche produit">×</button><div id="sf-detail-photo"></div><div><h2 id="sf-detail-title"></h2><p id="sf-detail-price"></p><label for="sf-detail-color">Couleur souhaitée (facultatif)</label><input id="sf-detail-color" placeholder="Ex. noir, rose, transparent"><p>Visuel illustratif. Version, couleur et disponibilité à confirmer pour votre téléphone.</p><button class="sf-primary" id="sf-add">Ajouter à ma sélection</button></div>';document.body.append(dialog);
  var active,trigger;dialog.querySelector('.sf-close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>trigger&&trigger.focus());dialog.querySelector('#sf-add').onclick=()=>{add(active,dialog.querySelector('input').value.trim());dialog.close()};
  function priceLink(p){var link=document.createElement('a');link.className='sf-price-wa';link.textContent='Demander le prix sur WhatsApp';link.setAttribute('aria-label','Demander le prix sur WhatsApp : '+p.name);link.target='_blank';link.rel='noopener';function refresh(){var model=$('#sf-device').value.trim();link.href=wa('quel est le prix du produit « '+p.name+' »'+(model?' pour mon '+model:'')+' ? Pouvez-vous également confirmer sa disponibilité ?')}refresh();link.addEventListener('click',refresh);link.addEventListener('focus',refresh);return link;}
  function open(p,b){active=p;trigger=b;dialog.querySelector('#sf-detail-title').textContent=p.name;var price=dialog.querySelector('#sf-detail-price');price.replaceChildren();if(p.price)price.textContent=p.price+' €';else price.append(priceLink(p));dialog.querySelector('#sf-detail-photo').replaceChildren(visual(p));dialog.querySelector('input').value='';var isCase=products.coques.includes(p);dialog.querySelector('input').hidden=!isCase;dialog.querySelector('label').hidden=!isCase;dialog.showModal()}
  function card(p){var a=document.createElement('article');a.className='sf-card';var b=document.createElement('button');b.type='button';b.append(visual(p));var label=document.createElement('small');label.textContent=p.note||p.brand||'SOLUTION ACCESSOIRES';var h=document.createElement('h3');h.textContent=p.name;var price=document.createElement('p');price.textContent=p.price?p.price+' €':'';var action=document.createElement('span');action.textContent='Choisir +';b.append(label,h,price,action);b.onclick=()=>open(p,b);a.append(b);if(!p.price){a.classList.add('sf-card-ask');a.append(priceLink(p))}return a;}
  function render(){var list=query?Object.values(products).flat().filter(p=>p.name.toLowerCase().includes(query.toLowerCase())):products[category];filters.hidden=!!query||category!=='coques';if(!filters.hidden){var style=$('#sf-case-style').value,brand=$('#sf-case-brand').value,sort=$('#sf-case-sort').value;list=list.filter(p=>(!brand||p.brand===brand)&&(!style||(style==='magsafe'&&/magsafe/i.test(p.name))||(style==='wallet'&&/wallet|folio|rabat/i.test(p.name))||(style==='clear'&&/transparent|clear/i.test(p.name))||(style==='color'&&!/transparent|clear|wallet|folio/i.test(p.name))));if(sort)list=list.slice().sort((a,b)=>a.price==null?1:b.price==null?-1:sort==='asc'?a.price-b.price:b.price-a.price);}$('#sf-grid').replaceChildren(...list.slice(0,limit).map(card));$('#sf-count').textContent=list.length?list.length+' modèles et coloris · '+Math.min(limit,list.length)+' affichés':'Aucun résultat. Essayez un autre terme ou contactez-nous.';$('#sf-more').hidden=list.length<=limit;root.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(!query&&b.dataset.category===category)));}
  $('#sf-more').onclick=()=>{limit+=8;render()};$('.sf-search').onsubmit=e=>{e.preventDefault();query=$('#sf-search').value.trim();limit=8;render()};$('#sf-show-glass').onclick=()=>{category='verres';query='';render()};render();
  products.hydrogel.forEach(p=>$('#sf-films').append(card(p)));
  var filmCaption=document.createElement('p');filmCaption.className='sf-disclaimer';filmCaption.textContent='Visuels des conditionnements fournisseur. Les prix affichés correspondent à une seule protection découpée et posée sur votre téléphone, pas à une boîte de films.';$('#sf-films').after(filmCaption);
  function updateBasket(){var list=$('#sf-basket');list.replaceChildren();basket.forEach((p,index)=>{var li=document.createElement('li');var text=document.createElement('span');text.textContent=p.name+(p.detail?' · '+p.detail:'')+(p.model?' · '+p.model:'')+' — '+(p.price?p.price+' €':'tarif à confirmer');var remove=document.createElement('button');remove.textContent='Retirer';remove.setAttribute('aria-label','Retirer '+p.name);remove.onclick=()=>{basket.splice(index,1);updateBasket()};li.append(text,remove);list.append(li)});if(!basket.length)list.textContent='Votre sélection est encore vide.';$('#sf-bag-count').textContent=basket.length;var total=basket.reduce((s,p)=>s+(p.price||0),0);$('#sf-total').textContent=basket.length?'Total des prix renseignés : '+total+' €'+(basket.some(p=>!p.price)?' + produits à chiffrer':''):'';var message='je souhaite des informations pour '+($('#sf-device').value.trim()||'mon téléphone (modèle à préciser)')+'.\n'+basket.map(p=>'- '+p.name+(p.detail?' / '+p.detail:'')+(p.model?' / '+p.model:'')+(p.price?' / '+p.price+' €':' / tarif à confirmer')).join('\n')+'\nPouvez-vous confirmer la compatibilité et la disponibilité avant mon passage ?';$('#sf-send').href=wa(message);$('#sf-mail').href='mailto:contact@solution-phone.fr?subject=Ma%20sélection%20boutique&body='+encodeURIComponent('Bonjour, '+message);}
  $('#sf-device').addEventListener('input',updateBasket);updateBasket();
  root.querySelectorAll('[data-service]').forEach(a=>{a.href=wa(a.dataset.service);a.target='_blank';a.rel='noopener'});$('.sf-stock-help').href=wa('je cherche un smartphone reconditionné. Mon modèle souhaité et mon budget : ');
  var stockItems=[],stockBusy=false,stockTime='',stockBrand='all';
  var stockFilters=document.createElement('div');stockFilters.className='sf-stock-brands';stockFilters.setAttribute('role','group');stockFilters.setAttribute('aria-label','Filtrer les appareils par marque');
  [['all','Tous'],['apple','iPhone'],['samsung','Samsung'],['other','Autres']].forEach(([value,label])=>{var button=document.createElement('button');button.type='button';button.textContent=label;button.setAttribute('aria-pressed',String(value===stockBrand));button.addEventListener('click',()=>{stockBrand=value;stockFilters.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));if(stockTime)renderStock()});stockFilters.append(button)});
  $('.sf-board-tools').before(stockFilters);
  function stockFamily(p){var name=String(p.modele).toLowerCase();if(/iphone|^se\s*[23]?$|^\d+\s*pro\s*max$/.test(name))return 'apple';if(/samsung|galaxy|z\s*flip|z\s*fold/.test(name))return 'samsung';return 'other'}
  function renderStock(){
    var query=$('#sf-stock-search').value.trim().toLocaleLowerCase('fr');
    var rows=stockItems.filter(p=>(stockBrand==='all'||stockFamily(p)===stockBrand)&&[p.modele,p.stockage,p.couleur,p.grade].join(' ').toLocaleLowerCase('fr').includes(query));
    var body=$('#sf-stock-rows');body.replaceChildren();
    rows.forEach(p=>{
      var tr=document.createElement('tr');
      var capacity=p.stockage?String(p.stockage).replace(/\s*(go|gb)$/i,'')+' Go':'Capacité à confirmer';
      var battery=Number(p.batterie);var condition=p.grade?'Grade '+p.grade:'État à confirmer';
      var batteryText=battery>0&&battery<=100?'Batterie '+battery+' %':'Batterie à confirmer';
      var model=document.createElement('td'),state=document.createElement('td'),availability=document.createElement('td'),price=document.createElement('td');
      var title=document.createElement('strong');title.textContent=p.modele;
      var details=document.createElement('small');details.textContent=[capacity,p.couleur].filter(Boolean).join(' · ');model.append(title,details);
      var grade=document.createElement('strong');grade.textContent=condition;var health=document.createElement('small');health.textContent=batteryText;state.append(grade,health);
      var badge=document.createElement('span');badge.className='sf-stock-badge';badge.textContent='Disponible';availability.append(badge);
      var amount=document.createElement('strong');amount.textContent=Number(p.vente).toLocaleString('fr-FR')+' €';
      var contact=document.createElement('a');contact.className='sf-reserve';contact.textContent='Réservez-le ↗';contact.target='_blank';contact.rel='noopener';contact.title='Demander une réservation sur WhatsApp, confirmée par notre équipe';contact.setAttribute('aria-label','Demander la réservation du '+p.modele+' '+capacity+' à '+p.vente+' euros sur WhatsApp');contact.href=wa('je souhaite réserver ce téléphone : '+p.modele+' · '+details.textContent+' · '+condition+' · '+batteryText+' · '+amount.textContent+'. Pouvez-vous me confirmer sa disponibilité et ma réservation ? Mon passage prévu en boutique : ');price.append(amount,contact);
      tr.append(model,state,availability,price);body.append(tr);
    });
    if(!rows.length){var empty=document.createElement('tr'),cell=document.createElement('td');cell.colSpan=4;cell.textContent=query?'Aucun appareil ne correspond à votre recherche.':'Aucun appareil disponible dans le catalogue pour le moment.';empty.append(cell);body.append(empty)}
    $('#sf-stock-status').textContent=rows.length+' appareil'+(rows.length===1?'':'s')+' affiché'+(rows.length===1?'':'s')+' / '+stockItems.length+' disponibles · Dernier chargement à '+stockTime;
  }
  async function loadStock(){
    if(stockBusy)return;stockBusy=true;$('#sf-stock-refresh').disabled=true;
    try{
      var response=await fetch('https://kdvxcnjfrmvlnrymfyug.supabase.co/functions/v1/public-catalog?resource=stock',{signal:AbortSignal.timeout(12000),cache:'no-store'});
      if(!response.ok)throw Error();var data=await response.json();if(!Array.isArray(data.stock&&data.stock.used))throw Error();
      stockItems=data.stock.used.filter(p=>p.modele&&Number(p.vente)>0);stockTime=new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'});renderStock();
    }catch(error){stockItems=[];$('#sf-stock-rows').replaceChildren();$('#sf-stock-status').textContent='Stock indisponible pour le moment. Contactez-nous pour connaître les appareils disponibles.'}
    finally{stockBusy=false;$('#sf-stock-refresh').disabled=false}
  }
  $('#sf-stock-search').addEventListener('input',()=>{if(stockTime&&stockItems.length)renderStock()});
  $('#sf-stock-refresh').addEventListener('click',loadStock);loadStock();
  setInterval(()=>{if(!document.hidden)loadStock()},60000);
  var slides=$('.sf-slides'),index=0;function slide(n){index=(n+3)%3;slides.scrollTo({left:index*slides.clientWidth,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}$('#sf-prev').onclick=()=>slide(index-1);$('#sf-next').onclick=()=>slide(index+1);slides.addEventListener('scroll',()=>{index=Math.round(slides.scrollLeft/slides.clientWidth);$('#sf-slide-status').textContent=(index+1)+' / 3'},{passive:true});
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
