/* Relevé visuel du catalogue public Utopya le 22/09/2026.
 * Source : https://www.utopya.fr/protection/iphone/iphone-15.html
 * Visuels illustratifs iPhone 15, compatibilité autres appareils à confirmer.
 * Aucun stock fournisseur ni prix d'achat importé. Prix publics selon gammes validées.
 */
window.utopyaCases = (function(){
 const base='https://www.utopya.fr/media/catalog/product/cache/361213619c8483dcf525ed41a38dd6e5/';
 const rows=[
 ['COVERME WEAVE MagSafe — Lilas','1/-/1-weave-violetclair_2.jpg',10],
 ['COVERME WEAVE MagSafe — Vert clair','1/-/1-weave-vertclair_1.jpg',10],
 ['COVERME WEAVE MagSafe — Orange','1/-/1-weave-orange_2.jpg',10],
 ['COVERME WEAVE MagSafe — Violet','1/-/1-weave-violet_2.jpg',10],
 ['COVERME WEAVE MagSafe — Bleu','1/-/1-weave-bleu_2.jpg',10],
 ['COVERME WEAVE MagSafe — Noir','1/-/1-weave-noir_2.jpg',10],
 ['COVERME CANVAS MagSafe — Noir','n/o/noir_18.jpg',10],
 ['COVERME CANVAS MagSafe — Violet foncé','v/i/violet_fonce__14.jpg',10],
 ['COVERME CANVAS MagSafe — Orange','o/r/orange_1_1.jpg',10],
 ['COVERME CANVAS MagSafe — Vert','v/e/vert_5.jpg',10],
 ['COVERME CANVAS MagSafe — Bleu marine','b/l/bleu_marine_3.jpg',10],
 ['COVERME GRAVITY MagSafe — Violet','0/1/01-gravity_magsafeviolet.jpg',10],
 ['COVERME GRAVITY MagSafe — Noir','0/1/01-gravity_magsafenoir.jpg',10],
 ['COVERME GRAVITY MagSafe — Bleu','0/1/01-gravity_magsafebleu.jpg',10],
 ['COVERME GRAVITY MagSafe — Blanc','0/1/01-gravity_magsafeblanc.jpg',10],
 ['COVERME Skin MagSafe — Rose pastel','0/1/01-ckinmagpastel_3.jpg',10],
 ['COVERME Skin MagSafe — Lilas','0/1/01-ckinmaglilas_1_2.jpg',10],
 ['COVERME Skin MagSafe — Noir','0/1/01-cskinmagnoir00_5.jpg',10],
 ['COVERME Skin MagSafe — Bleu saphir','0/1/01-cskinmagbleu00_5.jpg',10],
 ['COVERME HAZE MagSafe — Violet','0/0/0001-hazeviolet000_4.jpeg',10],
 ['COVERME HAZE MagSafe — Noir','0/0/001-hazenoir00_4.jpeg',10],
 ['COVERME HAZE MagSafe — Bleu','0/0/001-chazebleu001-0000_4.jpg',10],
 ['COVERME HALO MagSafe — Noir titane','c/o/coque_noir-5_6.png',10],
 ['COVERME HALO MagSafe — Gold','c/o/coque_dor_-5_6.png',10],
 ['COVERME HALO MagSafe — Rose gold','c/o/coque_rose-5_6.png',10],
 ['COVERME HALO MagSafe — Argent','c/o/coque_argent-5_6.png',10],
 ['COVERME HALO MagSafe — Bleu saphir','c/o/coque_bleufonc_-4_6.png',10],
 ['COVERME HALO MagSafe — Violet cosmos','c/o/coque_rose-4_6.png',10],
 ['COVERME HALO MagSafe — Vert boréal','c/o/coque_vert_6.png',10],
 ['COVERME HALO MagSafe — Bleu polaris','c/o/coque_bleu-1_6.png',10],
 ['Metal Ring MagSafe — Transparent','8/3/835--ip14pm-bolt-_8.jpg',10],
 ['Metal Ring MagSafe — Noir','8/3/838--coque-metal-ring-noir_7.jpg',10],
 ['COVERME TPU MagSafe — Transparent','_/5/_54a3743_6.jpg',10],
 ['FAIRPLAY POLARIS 2M MagSafe','1/-/1--polarisv2mag_12.jpg',10],
 ['COVERME Wallet à rabat — Marron','1/-/1--walletmarron_1_5.jpg',15],
 ['COVERME Wallet à rabat — Bleu','1/-/1--walletbleu_3_2.jpg',15],
 ['COVERME Wallet à rabat — Rouge','1/-/1--walletrouge_3_2.jpg',15],
 ['COVERME Wallet à rabat — Noir','1/-/1--walletnoir_4_2.jpg',15],
 ['FAIRPLAY RIGEL Folio MagSafe','3/2/326--rigel.jpg',15],
 ['COVERME PHANTOM — Violet','c/o/copie_de_2phantom_6.jpeg',10],
 ['COVERME PHANTOM — Bleu roi','c/o/copie_de_5phantom_9.jpeg',10],
 ['COVERME PHANTOM — Noir','c/o/copie_de_phantom_9.jpeg',10],
 ['COVERME STARDUST — Rose','0/1/01-rosestardust00_3.jpeg',10],
 ['COVERME STARDUST — Gris','0/1/01-grisstardust00_3.jpeg',10],
 ['COVERME STARDUST — Argent','0/1/01-argentstardust00_3.jpeg',10],
 ['Coque silicone — Noir','1/-/1-_4.jpg',10],
 ['Finger Grip — Vert pastel','f/i/fingergrip-cyan_8.jpg',10],
 ['COVERME TPU classique — Transparent','_/5/_54a3748_2_2.jpg',5],
 ['COVERME Anneaux — Transparent','9/0/908--coverme_7.jpg',null],
 ['COVERME Miroir — Cordon blanc','m/i/miror_6.jpg',null],
 ['COVERME Miroir — Cordon noir','7/-/7-miror_7.jpg',null],
 ['RHINOSHIELD JellyTint MagSafe — Noir','9/9/999--12345.jpeg',null],
 ['RHINOSHIELD Clear Case MagSafe','0/1/01-4711366126759.jpg',null],
 ['RHINOSHIELD SolidX MagSafe — Gris argent','0/-/0--solmaggris_20.jpeg',null],
 ['RHINOSHIELD SolidX MagSafe — Blanc','0/-/0--solmagblanc.jpeg',null],
 ['RHINOSHIELD SolidX MagSafe — Noir','0/-/0--solmagnoir.jpeg',null],
 ['RHINOSHIELD SolidX MagSafe — Beige coquillage','0/-/0--solmagbeico.jpeg',null],
 ['RHINOSHIELD SolidSuit MagSafe — Classic noir','0/1/01-mst0129552.jpg',null],
 ['RHINOSHIELD SolidX MagSafe — Vert algue','0/-/0--solmagveal_2_4.jpeg',null],
 ['RHINOSHIELD SolidX MagSafe — Bleu glacier','0/-/0--solmagbleugla.jpeg',null],
 ['RHINOSHIELD SolidX MagSafe — Vert sauge','0/-/0--solmagsauge.jpeg',null],
 ['RHINOSHIELD SolidX MagSafe — Océan bleu','0/-/0--solmagblma_1.jpeg',null],
 ['RHINOSHIELD SolidX MagSafe — Bleu marée','0/-/0--solmagmar_e.jpeg',null],
 ['RHINOSHIELD SolidX — Bleu glacier','0/-/0--solmagbleugla_8.jpeg',null],
 ['RHINOSHIELD SolidX — Rose poudré','0/-/0--solmagrosepou_9.jpeg',null],
 ['RHINOSHIELD SolidX — Beige coquillage','0/-/0--solmagbeico_8.jpeg',null],
 ['RHINOSHIELD SolidX — Vert sauge','0/-/0--solmagsauge_11.jpeg',null],
 ['RHINOSHIELD SolidX — Noir','0/-/0--solmagnoir_8.jpeg',null],
 ['RHINOSHIELD SolidX — Bleu marée','0/-/0--solmagmar_e_8.jpeg',null],
 ['RHINOSHIELD SolidX — Océan bleu','0/-/0--solmagblma_7.jpeg',null],
 ['RHINOSHIELD JellyTint — Noir','9/9/992--12345.jpeg',null],
 ['RHINOSHIELD Clear Case','0/1/01-44711366125790.jpg',null],
 ['RHINOSHIELD SolidX — Blanc','b/_/b_nljlmhjklm.jpg',null],
 ['RHINOSHIELD SolidX — Gris argent','0/-/0--solmaggris_8.jpeg',null],
 ['RHINOSHIELD SolidX — Vert algue','0/-/0--solmagveal_1_2.jpeg',null]
 ];
 return rows.map(([name,path,price])=>({name,img:base+path,price,brand:name.startsWith('RHINOSHIELD')?'RHINOSHIELD':name.startsWith('FAIRPLAY')?'FAIRPLAY':'COVERME',note:'Visuel iPhone 15 · modèle à préciser',source:'https://www.utopya.fr/protection/iphone/iphone-15.html'}));
})();
