-- Retour visiteur sur les réponses d'Evan, sans donnée personnelle supplémentaire.

create table if not exists public.evan_knowledge_feedback (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.evan_conversations(id) on delete cascade,
  message_id bigint not null references public.evan_messages(id) on delete cascade,
  knowledge_id uuid not null references public.evan_knowledge(id) on delete cascade,
  helpful boolean not null,
  created_at timestamptz not null default now(),
  unique (message_id)
);

create index if not exists evan_knowledge_feedback_knowledge_idx
  on public.evan_knowledge_feedback (knowledge_id, created_at desc);

alter table public.evan_knowledge_feedback enable row level security;

create or replace function public.evan_record_knowledge_feedback(
  conversation_uuid uuid,
  knowledge_uuid uuid,
  is_helpful boolean
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  matched_message_id bigint;
  inserted_count integer;
begin
  select message.id into matched_message_id
  from public.evan_messages as message
  where message.conversation_id = conversation_uuid
    and message.role = 'evan'
    and message.knowledge_id = knowledge_uuid
  order by message.id desc
  limit 1;

  if matched_message_id is null then return false; end if;

  insert into public.evan_knowledge_feedback (
    conversation_id, message_id, knowledge_id, helpful
  ) values (
    conversation_uuid, matched_message_id, knowledge_uuid, is_helpful
  )
  on conflict (message_id) do nothing;

  get diagnostics inserted_count = row_count;
  if inserted_count = 0 then return false; end if;

  update public.evan_knowledge
  set
    helpful_count = coalesce(helpful_count, 0) + case when is_helpful then 1 else 0 end,
    not_helpful_count = coalesce(not_helpful_count, 0) + case when is_helpful then 0 else 1 end,
    updated_at = now()
  where id = knowledge_uuid;

  return true;
end;
$$;

revoke all on function public.evan_record_knowledge_feedback(uuid, uuid, boolean) from public;
grant execute on function public.evan_record_knowledge_feedback(uuid, uuid, boolean) to service_role;
